'use client';
import { useMemo, useState } from 'react';
import { Shell } from '@/components/Shell';
import { characters, defaultStyle, references, styles } from '@/lib/seed-data';
import { buildPrompt, promptTemplates, revisionModes, type PanelForm } from '@/lib/prompt';

const initial: PanelForm = { chapter: '1', scene: 'Honesty during exam', panelNumber: '1', shotType: 'medium shot', cameraAngle: 'eye level', pov: 'third-person observer', expression: 'concerned but determined', action: 'Arya notices a classmate trying to cheat and prepares to respond calmly', background: 'Indonesian junior high school classroom during an exam', lighting: 'bright natural morning light from windows', mood: 'tense but hopeful', aspectRatio: '9:16 vertical webtoon', additionalPrompt: 'preserve consistent school uniform details', negativePrompt: 'text, speech bubble, blurry face' };
const fields: (keyof PanelForm)[] = ['chapter','scene','panelNumber','shotType','cameraAngle','pov','expression','action','background','lighting','mood','aspectRatio','additionalPrompt','negativePrompt'];
export default function Generator(){
 const [form,setForm]=useState(initial); const [styleId,setStyleId]=useState(defaultStyle.id); const [selected,setSelected]=useState(['arya','sinta']); const [result,setResult]=useState<string>(); const [loading,setLoading]=useState(false);
 const style = styles.find(s=>s.id===styleId) || defaultStyle; const selectedChars = characters.filter(c=>selected.includes(c.id));
 const prompt = useMemo(()=>buildPrompt(form, style, selectedChars, references),[form,style,selectedChars]);
 async function generate(){ setLoading(true); const res = await fetch('/api/generate-image',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt, aspectRatio: form.aspectRatio, references})}); const json=await res.json(); setResult(json.imageUrl); setLoading(false); }
 return <Shell><div className="mb-6"><p className="text-sm font-bold text-amber-400">Panel Generator</p><h2 className="text-3xl font-black">Compose continuity-safe prompts and images</h2></div><div className="grid gap-6 xl:grid-cols-[1fr_.9fr]"><section className="card grid gap-4 md:grid-cols-2"><div><label>Style preset</label><select value={styleId} onChange={e=>setStyleId(e.target.value)}>{styles.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label>Selected characters</label><select multiple value={selected} onChange={e=>setSelected(Array.from(e.target.selectedOptions).map(o=>o.value))}>{characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{fields.map(f=><div key={f} className={['action','additionalPrompt','negativePrompt','background'].includes(f)?'md:col-span-2':''}><label>{f}</label>{['action','additionalPrompt','negativePrompt','background'].includes(f)?<textarea rows={3} value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}/>:<input value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}/>}</div>)}<div className="md:col-span-2"><label>Prompt templates</label><div className="mt-2 flex flex-wrap gap-2">{promptTemplates.map(t=><button className="btn-secondary" key={t} onClick={()=>setForm({...form,additionalPrompt:[form.additionalPrompt,t].filter(Boolean).join(', ')})}>{t}</button>)}</div></div></section><aside className="space-y-6"><div className="card"><h3 className="text-xl font-bold">Final English prompt</h3><pre className="mt-4 max-h-[440px] overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-4 text-xs text-slate-300">{prompt}</pre><button disabled={loading} onClick={generate} className="btn mt-4">{loading?'Generating...':'Generate image'}</button></div><div className="card"><h3 className="text-xl font-bold">Revision mode</h3><div className="mt-3 flex flex-wrap gap-2">{revisionModes.map(r=><button key={r} className="btn-secondary" onClick={()=>setForm({...form,additionalPrompt:`${form.additionalPrompt}. Revision: ${r}.`})}>{r}</button>)}</div></div>{result&&<div className="card"><h3 className="text-xl font-bold">Generated panel</h3><img src={result} alt="Generated comic panel" className="mt-4 rounded-xl border border-slate-700"/><a download className="btn-secondary mt-4 inline-block" href={result}>Download</a></div>}</aside></div></Shell>;
}
